name: meteo_scraper
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - pip
  - pandas
  - selenium
  - r-base=4.5.2
  - r-car
  - r-caret
  - r-corrplot
  - r-dplyr
  - r-factoextra
  - r-future
  - r-future.apply
  - r-ggplot2
  - r-gridextra
  - r-kableextra
  - r-knitr
  - r-languageserver
  - r-laeken
  - r-magick
  - r-moments
  - r-ranger
  - r-rann
  - r-rmarkdown
  - r-robustbase
  - r-sf
  - r-sp
  - r-tidyverse
  - r-vcd
  - r-xgboost
  - r-bbotk
  - r-checkmate
  - r-lgr
  - r-mirai
  - r-mlbench
  - r-mlr3
  - r-mlr3measures
  - r-mlr3misc
  - r-mlr3pipelines
  - r-mlr3tuning
  - r-mlr3learners
  - r-nanonext
  - r-PRROC
  - r-palmerpenguins
  - r-paradox